# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2023-07"

[[extensions]]
type = "ui_extension"
name = "inStock"
handle = "instock"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

# [extensions.settings]
# [[extensions.settings.fields]]
# key = "banner_title"
# type = "single_line_text_field"
# name = "Banner title"
# description = "Enter a title for the banner"
 [settings]
   [[settings.fields]]
   key = "text"
   type = "single_line_text_field"
   name = "Block Text"
   description = "Block Text"

   [[settings.fields]]
   key = "indicatorUrl"
   type = "single_line_text_field"
   name = "Image Url Link"
   description = "Enter a url Link Copy & Past"

   [[settings.fields]]
   key = "image_size"
   type = "single_line_text_field"
   name = "Image Size"
   description = "Enter a number Between 1 to 100"

    [[settings.fields]]
    key = "image_text_space"
    type = "single_line_text_field"
    name = "Spacing Between Image and text"
    description = "Select Spacing Type"
    [[settings.fields.validations]]
    name = "choices"
     value = '["none", "base", "tight", "loose", "extraLoose", "extraTight", "large100", "large200", "large300", "large400", "large500", "small100", "small200", "small300", "small400", "small500"]'